Algoritmo "exercicio faccat"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Conta de 10 a 1 em ordem decrescente
// Autor(a)    : Samuel
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis

indice: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para indice de 10 ate 1 passo -1 faca
escreva (indice)
fimpara

Fimalgoritmo