Algoritmo "exercicio faccat"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Contador de 101 até 110
// Autor(a)    : Samuel
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis
indice: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para indice de 101 ate 110 faca
escreva (indice)
fimpara
Fimalgoritmo