Algoritmo "exercicio faccat"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : contador de 1 ate o numero escolhido
// Autor(a)    : Samuel
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis
indice: inteiro
numero: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("Digite um número: ")
leia (numero)
para indice de 1 ate numero faca
escreva (indice)
fimpara
Fimalgoritmo