Algoritmo "exercicio faccat"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Faz a tabuada do 8
// Autor(a)    : Samuel
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis
indice: inteiro
multiplicacao: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para indice de 1 ate 10 faca
multiplicacao <- 8 * indice
escreval ("8 X",indice, " =",multiplicacao)
fimpara
Fimalgoritmo