Algoritmo "exercicio faccat"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Escrever numeros de 1 ate 10 com um contador
// Autor(a)    : Samuel
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis
contador: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contador <- 1
repita
escreva(contador)
contador <- contador + 1
ate contador = 11
Fimalgoritmo