Algoritmo "exercicio faccat"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Escreva de 10 até 1 com um contador
// Autor(a)    : Samuel
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis
contador: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contador <- 10
enquanto contador <> 0 faca
escreva (contador)
contador <- contador - 1
fimenquanto
Fimalgoritmo