Algoritmo "semnome"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Solicitar dois numeros e exibir o resultado
// Autor(a)    : Samuel Caetano
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
resultado:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(numero1)
resultado<-numero1-(1)
escreval("Resultado: ",resultado)
Fimalgoritmo